name = "LandSea"
uuid = "cbf7bb22-a1a6-46cb-8b24-174e3bc5fc04"
authors = ["Nathanael Wong <natgeo.wong@outlook.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
